#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BackboardXamarin.Resource", IsApplication=true)]

namespace BackboardXamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BackboardLib.Resource.String.library_name = global::BackboardXamarin.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int circles = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int debug_blue = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int debug_gray = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int debug_green = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int debug_navy = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int debug_orange = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int debug_purple = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int debug_red = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int white = 2131099655;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int circle_gray = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int circle_green = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int circle_orange = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int circle_purple = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int circle_red = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int feedback = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int grid = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ring_navy = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int selected_photo = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001a
			public const int action_1 = 2131361818;
			
			// aapt resource value: 0x7f0a0013
			public const int action_appear = 2131361811;
			
			// aapt resource value: 0x7f0a0011
			public const int action_bloom = 2131361809;
			
			// aapt resource value: 0x7f0a0017
			public const int action_constrained = 2131361815;
			
			// aapt resource value: 0x7f0a0014
			public const int action_explosion = 2131361812;
			
			// aapt resource value: 0x7f0a0012
			public const int action_flower = 2131361810;
			
			// aapt resource value: 0x7f0a0015
			public const int action_follow = 2131361813;
			
			// aapt resource value: 0x7f0a000e
			public const int action_move = 2131361806;
			
			// aapt resource value: 0x7f0a0019
			public const int action_origami = 2131361817;
			
			// aapt resource value: 0x7f0a0018
			public const int action_press = 2131361816;
			
			// aapt resource value: 0x7f0a0010
			public const int action_scale = 2131361808;
			
			// aapt resource value: 0x7f0a000f
			public const int action_snap = 2131361807;
			
			// aapt resource value: 0x7f0a0016
			public const int action_zoom = 2131361814;
			
			// aapt resource value: 0x7f0a0008
			public const int circle = 2131361800;
			
			// aapt resource value: 0x7f0a0001
			public const int circle0 = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int circle1 = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int circle2 = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int circle3 = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int circle4 = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int circle5 = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int constraint = 2131361799;
			
			// aapt resource value: 0x7f0a0000
			public const int container = 2131361792;
			
			// aapt resource value: 0x7f0a000c
			public const int feedback = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int grid = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int rect = 2131361801;
			
			// aapt resource value: 0x7f0a000b
			public const int selection = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int spring_configurator = 2131361805;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_backboard = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fragment_appear = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fragment_bloom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fragment_constrain = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int fragment_flower = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int fragment_follow = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int fragment_move = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int fragment_press = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int fragment_scale = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int fragment_snap = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int origami_example = 2130968586;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int backboard = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050007
			public const int action_appear = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int action_bloom = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int action_constrained = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int action_explosion = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int action_flower = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int action_follow = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int action_move = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int action_origami = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int action_press = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int action_scale = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int action_snap = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int action_zoom = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
